import { LegalPageLayout } from "@/components/marketing/LegalPageLayout";

export const metadata = {
  title: "Disclaimer — FitPilot Pro",
  description: "Disclaimer for FitPilot Pro by Albor Digital LLC.",
};

export default function DisclaimerPage() {
  return (
    <LegalPageLayout
      title="Disclaimer"
      subtitle="Effective Date: January 1, 2026"
      lastUpdated="Albor Digital LLC"
    >
      <h2>1. General Disclaimer</h2>
      <p>
        FitPilot Pro and all other products, tools, data, and content provided
        by Albor Digital LLC are offered for informational and practical utility
        purposes only. While we strive for accuracy and usefulness, we make no
        representations or warranties — express or implied — regarding the
        completeness, accuracy, reliability, or suitability of any information or
        tool for any particular purpose. All use is at your own risk.
      </p>

      <h2>2. No Professional Advice</h2>
      <p>
        Nothing provided through FitPilot Pro constitutes legal, financial,
        medical, fitness, nutritional, investment, tax, or professional advice
        of any kind. The platform is a business management tool. Workout
        templates, progress data, and AI scheduling suggestions are operational
        aids for professional trainers — not medical or clinical guidance.
      </p>
      <p>
        Any data, analysis, or output generated by our tools — including
        AI-powered features — should not be relied upon as a substitute for
        advice from a qualified professional. Always seek independent
        professional guidance before making decisions based on our products.
      </p>

      <div className="callout">
        FitPilot Pro is a business management tool for fitness professionals. It
        is not a clinical platform, medical device, or health record system.
        Client health data entered into the platform is used solely to assist
        trainers in their professional practice.
      </div>

      <h2>3. AI-Generated Content</h2>
      <p>
        FitPilot Pro includes AI-powered features including an AI Scheduling
        Assistant powered by Anthropic&rsquo;s Claude API. AI outputs are
        generated algorithmically and may contain errors, omissions, or
        inaccuracies. AI-generated schedules, suggestions, and analysis reflect
        patterns in training data and do not represent verified professional
        recommendations, clinical opinions, or the views of Albor Digital LLC.
      </p>
      <p>
        Users are solely responsible for evaluating and verifying any
        AI-generated content before acting on it. All AI outputs within FitPilot
        Pro are labeled as AI-generated and are decision-support tools only. The
        trainer retains full professional responsibility for all client
        decisions.
      </p>

      <h2>4. Client Data and Health Information</h2>
      <p>
        FitPilot Pro enables trainers to record client health metrics, body
        composition data, progress photos, and related information. This data is
        entered and managed by the trainer. Albor Digital LLC does not review,
        validate, or act on client health data. Trainers are solely responsible
        for the accuracy of data entered and for compliance with any applicable
        health data privacy laws in their jurisdiction.
      </p>
      <p>
        FitPilot Pro is not HIPAA-compliant and is not designed for use in
        clinical, medical, or regulated healthcare settings.
      </p>

      <h2>5. Route Optimization and Maps</h2>
      <p>
        The route optimization feature uses the Google Maps Directions API to
        suggest driving routes between session locations. Suggested routes are
        for informational convenience only. Albor Digital LLC makes no guarantee
        of route accuracy, traffic conditions, or travel times. Users are
        responsible for their own navigation decisions and compliance with local
        traffic laws.
      </p>

      <h2>6. Business Analytics and Revenue Data</h2>
      <p>
        Revenue figures, session counts, and business analytics displayed in
        FitPilot Pro are derived from data that you enter into the platform.
        Albor Digital LLC does not verify the accuracy of this data and is not
        responsible for financial decisions made based on analytics shown within
        the product. Analytics are for informational reference only and do not
        constitute financial advice.
      </p>

      <h2>7. External Links</h2>
      <p>
        Our products may reference or link to external websites and resources.
        Albor Digital LLC does not control and is not responsible for the
        content, accuracy, or availability of external sites. Inclusion of a
        link does not imply endorsement.
      </p>

      <h2>8. Limitation of Liability</h2>
      <div className="uppercase-block">
        TO THE FULLEST EXTENT PERMITTED BY LAW, ALBOR DIGITAL LLC AND ITS OWNER
        SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL,
        OR PUNITIVE DAMAGES ARISING FROM RELIANCE ON OR USE OF FITPILOT PRO, ITS
        TOOLS, DATA, AI OUTPUTS, OR CONTENT — INCLUDING ANY ERRORS, INTERRUPTIONS,
        OR INACCURACIES THEREIN.
      </div>

      <h2>9. Jurisdictional Notice</h2>
      <p>
        FitPilot Pro is operated from Canada and the United States. We make no
        representation that our products are appropriate or available for use in
        all jurisdictions. Users who access our products from outside these
        regions do so at their own initiative and are responsible for compliance
        with local laws.
      </p>
    </LegalPageLayout>
  );
}
